apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-sample-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-sample-backend
  minReadySeconds: 5
  progressDeadlineSeconds: 90
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0
  template:
    metadata:
      labels:
        app: aks-sample-backend
        version: v1
    spec:
      securityContext:
        runAsUser: 1000
      imagePullSecrets:
        - name: docker-reg-credential
      containers:
        - name: aks-sample-backend
          image: team20registory.azurecr.io/aks-sample/test-backend:0.0.1
          env:
            - name: TZ
              value: JST-9
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:InitialRAMPercentage=50 -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=50 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -XX:InitialCodeCacheSize=64m -XX:ReservedCodeCacheSize=64m -XX:CompressedClassSpaceSize=64m -XX:NewRatio=1 -XX:+UseParallelGC -Xlog:gc*=info::time,uptime,level,tags -XX:+ExitOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
            - name: SPRING_PROFILES_ACTIVE
              value: "pr"
            - name: DATASOURCE_URL
              value: WRITE YOUR PRODUCTION DATABASE CONNECTION URL HERE
            - name: DATASOURCE_USER
              value: WRITE YOUR PRODUCTION DATABASE LOGIN USERNAME HERE
            - name: DATASOURCE_PASSWORD
              value: WRITE YOUR PRODUCTION DATABASE LOGIN PASSWORD HERE
            - name: REDIS_HOST
              value: WRITE YOUR PRODUCTION REDIS HOST URL HERE
            - name: REDIS_PORT
              value: WRITE YOUR PRODUCTION REDIS PORT NUMBER HERE
            - name: REDIS_PASSWORD
              value: WRITE YOUR PRODUCTION REDIS PASSWORD HERE
          livenessProbe:
            httpGet:
              path: /spring-boot-aks/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /spring-boot-aks/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 1G
            limits:
              cpu: 500m
              memory: 1.5G
