apiVersion: v1
kind: Service
metadata:
  labels:
    app: aks-sample-backend-load-balancer
  name: aks-sample-backend-load-balancer
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: aks-sample-backend
  sessionAffinity: None
  type: LoadBalancer
